name: Checkout and lint

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - 'release/**'

  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          # speed actions run https://github.com/actions/setup-node#caching-global-packages-data
          cache: 'npm'
      - name: Install dependencies and run lint
        run: npm run build:dev:ci
      - name: Run linter
        run: npm run lint
