name: Playwright Tests
on:
  workflow_dispatch:

  push:
    branches:
      - main
      - 'release/**'

  pull_request:
    branches:
      - main
      - 'release/**'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.13]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        # speed actions run https://github.com/actions/setup-node#caching-global-packages-data
        cache: 'npm'
    - name: Install dependencies
      run: npm run build:dev:ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: tests/playwright-report/
        retention-days: 30
